# Generated by Django 2.2.7 on 2020-03-31 01:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, IntegrityError
from django.conf import settings
import jsonfield.fields
import kpi.fields.lazy_default_jsonb

from kpi.management.commands.populate_asset_jsonbfields \
    import populate_asset_jsonbfields


SKIP_HEAVY_MIGRATIONS_MESSAGE = '''
!!! ATTENTION !!!
April 2020 -- Data migration needed

kpi migration 0025 initiates the migration of the following fields from TEXT
to JSONB:

  text field                  jsonb field
  ----------                  -----------
* asset.content  ->           asset.content_jsonb
* asset.summary  ->           asset.summary_jsonb
* asset._deployment_data  ->  asset._deployment_data_jsonb

Directions for removing the old columns will be released in a future
update to minimize risk of data loss.

To continue with future migrations, you will need to run the following
management command.

   > python manage.py populate_asset_jsonbfields

Your KoBo server can stay up and running during this migration
'''

POTENTIALLY_SLOW_MIGRATION_MESSAGE = '''
Running `populate_asset_jsonbfields` on existing assets.

This might take a while. If it is too slow, you will want to cancel this task
and re-run the migration with SKIP_HEAVY_MIGRATIONS=True and run the management
command (populate_asset_jsonbfields) in the background to prepare the assets.

This command does not require downtime.
'''


SKIP_HEAVY_MIGRATIONS = settings.SKIP_HEAVY_MIGRATIONS


def forwards_func(apps, schema_editor):
    if SKIP_HEAVY_MIGRATIONS:
        print(SKIP_HEAVY_MIGRATIONS_MESSAGE)
    else:
        print(POTENTIALLY_SLOW_MIGRATION_MESSAGE)
        populate_asset_jsonbfields()


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0025_delete_collections_fix_asset_parent_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='_deployment_data_jsonb',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='content_jsonb',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='summary_jsonb',
            field=kpi.fields.lazy_default_jsonb.LazyDefaultJSONBField(default=dict),
        ),
        migrations.RunPython(forwards_func, noop),
    ]
